### ISSUE TITLE
Create 'Update Event' Page

### ISSUE THREAD

**Issue by erikNeville** [ActoKids/AD440_W19_CloudPracticum#38]

**Comment by zphupro** [comment]
Create an update event page to allows create the complete form for updating the event and when you want to change info from the event the button is clicked you I will research and figure out on How to  update using React library and how to create radio buttons and How to show radio option in two columns 
Estimated time: 10 hours
Actual time:

**Comment by zphupro** [comment]
So far, I  spent the time to do research on reacts how to use and how it works then I Created a react web application localhost with radio event list and submit button. The challenge so far has been learning myself how to use react and how to create react apps It took  3 hours on this UI web task.

**Comment by zphupro** [comment]
This is my result so far 
![updateandcreateevent](https://user-images.githubusercontent.com/38090459/52024283-2a5e1480-24b5-11e9-8260-ec8c5a89fc8b.jpg)

**Comment by zphupro** [comment]
test link : http://actokids-updateevent.s3-website-us-east-1.amazonaws.com/

**Comment by zphupro** [comment]
Estimated : 10 hours 
Time spent : 9 hours 


For this task, I spent a lot of the time to do research a lot on reacting because this new to me and I don't know how to use and how it works for the first time.  then sometimes when I create I Created a react web application localhost with radio event list and submit button but doesn't include CSS. That is my first trouble. It does The challenge so far has been learning myself how to use react and how to create react apps It took 3 hours on this UI web task. and 6 hours to figure out to the form but it not perfect yet. 
I using material-UI instead of bootstrap to do this task
Deployed code link: LIVE Demo http://actokids-updateevent.s3-website-us-east-1.amazonaws.com/
GitHub : https://github.com/ActoKids/web-ui/tree/Phu-uploadevent

**Comment by zphupro** [comment]
![3](https://user-images.githubusercontent.com/38090459/52385681-8d145a80-2a37-11e9-838d-cf83c1fb9fb5.JPG)
![4](https://user-images.githubusercontent.com/38090459/52385685-900f4b00-2a37-11e9-90d2-05000ee49a33.JPG)
![6](https://user-images.githubusercontent.com/38090459/52385692-9a314980-2a37-11e9-985a-9d788ef5df82.JPG)

**Comment by zphupro** [comment]
![5](https://user-images.githubusercontent.com/38090459/52385712-a9b09280-2a37-11e9-955f-1a6bfc6d5e98.JPG)

**Comment by zphupro** [comment]
github : https://github.com/ActoKids/web-ui/tree/Phu-uploadevent

**Comment by toddysm** [comment]
Need the following:
- Link to Pull Request
- Link to Wiki Page
- Link to working prototype
- Who tested this and what is the feedback?
- What did you test and what is the feedback?

**Comment by zphupro** [comment]
* Link to Pull Request: https://github.com/ActoKids/web-ui/pull/13
* Link to Wiki Page: https://github.com/ActoKids/web-ui/wiki/Update-Event-task
* Link to working prototype :  http://actokids-updateevent.s3-website-us-east-1.amazonaws.com/
* Who tested this and what is the feedback?
HKHUAL AND BRADLEYSHAO  ON PULL REQUEST
HKHUAL SAID: I have reviewed the changes. It looks good. keep up the good work.
BRADLEYSHAO: looks good
* What did you test and what is the feedback?
I run the website in localhost and my AWS website they show correct position form and when I typed all info it saves in next page to review and then submits it said success page.

**Comment by zphupro** [comment]
updated: because our brach now use the same format so I need merge to a different one this is my update 
* Link to Pull Request: https://github.com/ActoKids/web-ui/pull/22
* Link to Wiki Page: https://github.com/ActoKids/web-ui/wiki/Update-Event-(-new-Page-)
