### ISSUE TITLE
UI Forms: Delete Event>DELETE/events/{id}

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#50]
Connect forms to corresponding API endpoints: Delete Event>DELETE/events/{id}

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:

**Comment by yahya09206** [comment]
Time estimated: 1-2 hours 
Time spent so far: 8 hrs
Pull Request link: https://github.com/ActoKids/web-ui/pull/57
Wiki link: https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/UI-Forms:-Delete-Event-DELETE-events-%7Bid%7D
Deployed Code link: deployed to prod but interfered with a bigger task like the filter function, so had to revert to not using delete.
Tested by: Erik & Hau
What I tested: I tested the delete function by checking off one event and deleting it, refreshing the page and making sure that event was actually deleted from the db and not showing up again on the dashboard.

Doing research on how to delete using react. First time working with this framework so the time estimated is based on learning some of the language as well to help me complete the task. Will update as I start to progress. I was few merges behind due to working with aws and travis ci when I started coding so trying to understand the codebase and learn how it was working took some time as well hence why my estimated time and time actually spent were way different.

-Shows event before deletion
<img width="1068" alt="Screen Shot 2019-03-20 at 4 15 50 PM" src="https://user-images.githubusercontent.com/10914845/54728446-31abb100-4b3b-11e9-9cd2-27f499704761.png">

-Delete two events at the same time
<img width="1055" alt="Screen Shot 2019-03-20 at 4 16 12 PM" src="https://user-images.githubusercontent.com/10914845/54728463-40926380-4b3b-11e9-94d7-675e4ef134e9.png">

-Shows event that was under the previous two that were deleted from db
<img width="1113" alt="Screen Shot 2019-03-20 at 4 16 22 PM" src="https://user-images.githubusercontent.com/10914845/54728468-44be8100-4b3b-11e9-8c50-ed5392f98ace.png">
