### ISSUE TITLE
UI Forms: Update Event>PUT/events/{id}

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#51]
Connect forms to corresponding API endpoints: Update Event>PUT/events/{id}

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:

**Comment by zphupro** [comment]
This task I am going to create the form as json when I click submit button then its will send json file to the API endpoint 
Time estimated:  10 hours
Time spent:

**Comment by zphupro** [comment]
Time estimated 10 hours 
Time spent: 10 hours need to research how to save as JSON file and upload to endpoint so far I make the form working and I using JSON server in node js and when I go to form and type it. Its make change in JSON file. ITs hard the begin when making the form as JSON file.

**Comment by zphupro** [comment]
I created a fake JSON data
![2](https://user-images.githubusercontent.com/38090459/53138222-6d525b80-353a-11e9-82d3-385a30289db5.JPG)
when I make some change in form 👍 
![3](https://user-images.githubusercontent.com/38090459/53138226-704d4c00-353a-11e9-86b8-f036ec926b8d.JPG)
This is what I got when I change the name :
![4](https://user-images.githubusercontent.com/38090459/53138229-717e7900-353a-11e9-84c6-53f9dbf16e93.JPG)

**Comment by zphupro** [comment]
Pull Request link: https://github.com/ActoKids/web-ui/pull/23
Wiki link:  https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/Update-Event-PUT-events-%7Bid%7D

**Comment by zphupro** [comment]
i am still working on it because i need figure more about json and api endpoint

**Comment by zphupro** [comment]
Time estimated 10 hours
Time spent: 10 hours need to research how to save as JSON file and upload to endpoint so far I make the form working and I using JSON server in node js and when I go to form and type it. Its make change in JSON file. ITs hard the begin when making the form as JSON file.
* Link to Pull Request : https://github.com/ActoKids/web-ui/pull/23
* Link to Wiki Page : https://github.com/ActoKids/web-ui/wiki/Update-Event-PUT-events-%7Bid%7D
* Link to working prototype :  http://actokids-updateevent.s3-website-us-east-1.amazonaws.com/update
* Who tested this and what is the feedback?
hau test my form and he said that Tested, no conflict with dev branch. Can merge.
* What did you test and what is the feedback?
I did a test on yitong 's  Create>POST/events sprint 3 I clone his part to my local machine and then I delete all file from node_module and type npm install and npm start because doesn't have API link yet then I install json server to test his file when I pasted json model to db.json from json server  then when i run his page when i type all information then i come back localhost:3000/values to check and it had all data i input. So far, everything work great and he did very good job . i run it and no problem
