### ISSUE TITLE
Configure Prod endpoint

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#63]
Configure Prod endpiont and work with DevOps to test automation.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated: 
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by erikNeville** [comment]
I will be working with Dawitt to accomplish this task. I have just completed connecting the dashboard to a mock up API, and will be starting this task on Thursday, 2/28.
I will have a working link to the Prod endpoint which will show my code.

Estimated time: 12 hrs

**Comment by erikNeville** [comment]
I've uploaded build files to the S3 bucket, 2edusite.com. I ran `npm run build` in command prompt while within the project's root folder which creates a build folder containing everything needed to deploy the website. However I seem to be getting errors which I assume are related to my access permissions within AWS, as seen in this screenshot.
![objectlock](https://user-images.githubusercontent.com/27576296/53844986-56f5c800-3f5c-11e9-8caf-1ed1fcf18bcc.PNG)

Dawitt is helping me on the DevOps side, to resolve this bug.

Time spend so far: 5 hours

Edit: The page is now properly displayed at 2edusite.com and www.2edusite.com with a redirect. The issue now is that the build package from `npm run build` contains files that need to be public in order to make calls to each other. Neither myself of Dawitt are able to make these files public at the moment, and we are working to resolve this.

**Comment by erikNeville** [comment]
I've uploaded the build files to the ak-ui-prod-s3 S3 bucket. Because of our Route53 targeting CloudFront distribution (because Route53 does not support HTTPS) we are targeting the ak-ui-prod-s3 bucket without using a matching domain bucket. 

Reviewed Dawitt's Code: https://github.com/ActoKids/devops/pull/40#pullrequestreview-211480465
Reviewed Hau's Code: https://github.com/ActoKids/web-ui/pull//28#pullrequestreview-210973935
Links to Prod Endpoints: [2edusite.com](url), www.2edusite.com
Pull Request: I have no pull request link for this sprint because my work was done within the AWS Console, but the link to the bucket is here: https://s3.console.aws.amazon.com/s3/buckets/ak-ui-prod-s3/?region=us-east-2&tab=overview
Wiki Page: https://github.com/ActoKids/web-ui/wiki/Dashboard

Estimated Time: 12 hrs
Total Time: 9 hrs

**Comment by dashinay** [comment]
I have reviewed the created endpoints 2edusite.com and www.2edusite.com, and both functioned well. Though I had to switch back to old configuration where we had two buckets because of unexpected issues with www.2edusite.com enpoint(Access Denied)
