### ISSUE TITLE
List Events calling the API

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#66]
Implement the API to list the events.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated: 
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by hkhual** [comment]
I will be working with API team to get API calling function working properly on the app. And testing to make sure it is displaying correctly on the page.  
Estimated Time: 4 Hours
Time Spent: TBD

**Comment by hkhual** [comment]
I have contacted Alex from the API Team and asked whom should I contact in API Team for list Events calling API. I received a working API Endpoint from Alex and tested. 
The API endpoint Alex gave me: https://api-zakb.2edusite.com/v1/v1/events

**Comment by hkhual** [comment]
I have contacted Zak Brinlee for GET API endpoint, because the one I received from Alex no longer work. I have received a new GET API endpoint from Zak.  
A new Endpoint from Zak. https://api-zakb.2edusite.com/v1/events
It looks like they have changed the path, that's why I wasn't able to access to their GET API. Here is the issue created by API team https://github.com/ActoKids/api/issues/47 regard to change on base path.

**Comment by hkhual** [comment]
I fixed the merge conflict in Erik pull request. https://github.com/ActoKids/web-ui/pull/25.

**Comment by hkhual** [comment]
I will be doing research on how to filter fetch API data.

**Comment by hkhual** [comment]
Pull request link: https://github.com/ActoKids/web-ui/pull/28

**Comment by hkhual** [comment]
I ran into a problem in AWS S3 when I tried to access get Event from its link. 
![error 404 in aws s3](https://user-images.githubusercontent.com/24612635/53860461-fe432100-3f95-11e9-80f8-1194c84ce5d5.JPG)

**Comment by hkhual** [comment]
I found a stack overflow question regarding to 404 not found error. https://stackoverflow.com/questions/51218979/react-router-doesnt-work-in-aws-s3-bucket 
It's because AWS S3 is looking for that folder (get) to serve from, which I don't have.
Simply pointing Error document to index.html fixed the problem. 

![actokids aws s3 static hosting](https://user-images.githubusercontent.com/24612635/53860809-0f406200-3f97-11e9-9ee4-9a1ecad78670.JPG)

**Comment by hkhual** [comment]
**This is the Dashboard page, basically a homepage .**
![dashboard homepage](https://user-images.githubusercontent.com/24612635/53867193-2dfb2480-3fa8-11e9-8e1a-a810bb1ce5c4.JPG)

**This is a List Event page. Here you can see, it is displaying data from API. https://api-zakb.2edusite.com/v1/events** 
![fetching data from remote api](https://user-images.githubusercontent.com/24612635/53867311-6f8bcf80-3fa8-11e9-8270-840e437e4151.JPG)

**Comment by hkhual** [comment]
Time Estimated: 4 hours
Time spent: 6 hours
pull request link: https://github.com/ActoKids/web-ui/pull/28
Wiki link: https://github.com/ActoKids/web-ui/wiki/List-Events-from-API
Deployed Code link:: http://actokids.s3-website-us-east-1.amazonaws.com/get


**Who test this and what is the feedback?**
Yithong and Erik tested listEvent page. They run a test on their own machines and say everything work fine, no bug/error or merge conflict.  

**What did you test and what is the feedback?**
I tested Erik's branch pull request https://github.com/ActoKids/web-ui/pull/25 and found that it has merge conflict files. I was able to fix his merge conflict files. 
I also tested Erik new pull request. https://github.com/ActoKids/web-ui/pull/27 to make sure there is no issue on his branch or conflict files.
I tested Danielle pull request https://github.com/ActoKids/web-ui/pull/31 and added appliedRoute.js I got from Danielle to fix sign in issue. Now the sign in page is working.
