### ISSUE TITLE
Bug: Confirm Cognito config, UITeam/API Team

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#87]
Under Sprint 4 [issue #65](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/65) Login page connecting to Cognito, there is a configured version on the ActoKids AWS account under API Team's Cognito. 

-Environment
AWS Console

-Current Behavior
Connecting to @ZakBrinlee's AWS Congito

-Expected Behavior
Using AD440's AWS account Cognito (UI Team specifically) 

-Additional Documentation
See [Bug #77 UI Team Permissions ](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/77)

**Comment by coultergeist** [comment]
There are two Cognito functions:
1) "Manage User Pools" - I am able to fully create a user pool.
2) "Manage Identity Pools" - Not authorized 
`User: arn:aws:iam::061431082068:user/danielle.coulter@seattlecolleges.edu is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::061431082068:role/Cognito_ActoKidsAuth_Role`

Note: I (believe) I need DevOps to create a policy and a role that allows the people logging in to actually invoke the API.

**Comment by coultergeist** [comment]
Hours to Date: 11

### Coding for User Login
Complete. Right now users can successfully log in (with API Team Cognito User Pool)

exerpt from `config.js` file:
`/* This is the UI Team Cognito Info. Remove above cognito info an uncomment this out`

`cognito: {`
		`REGION: 'us-east-2',`
		`USER_POOL_ID: 'us-east-2_otpHbMxKi',`
		`APP_CLIENT_ID: '7l7q1utlnmg3qnmlffc5n4otin',`
		`IDENTITY_POOL_ID: '' //this will be created once Cognito Perms are corrected`
	`} */`

<img width="1038" alt="login" src="https://user-images.githubusercontent.com/16545169/53915015-ddb9ac00-4013-11e9-89a8-0d232ff65122.png">

Once logged in, the user is successfully directed to Dashboard
<img width="1023" alt="dashboard" src="https://user-images.githubusercontent.com/16545169/53915030-ea3e0480-4013-11e9-8243-f0fb84dacc63.png">

**Comment by ZakBrinlee** [comment]
I can confirm that Danielle and I were able to get the Cognito Login working using my AWS Cognito account. We are currently working on getting the correct permissions in order to set up Cognito on the AD 440 AWS account. 

Once this is completed Danielle will be able to update the config with the AD 440 Cognito configuration. 

The screenshot below is of the confirmed two users using my AWS Cognito configuration. 
<img width="1255" alt="cognitouserpool" src="https://user-images.githubusercontent.com/22527777/53917648-e6ad7c00-4019-11e9-86b6-5d6e5eb483c8.PNG">

**Comment by coultergeist** [comment]
Successfully connecting to Cognito. Issue resolved and closed.
