### ISSUE TITLE
User logged in logic

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#93]
For this final sprint, create logic to determine if a user is signed in or not. Also, need to Hide/Show 

### Nav bar
1) Remove Sign with Log (ie: Log in, Log out)
2) Hide/Show Login functions: (see [issue # 92](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/92) for User logged in logic)
- Login button. Should only appear if user is not logged in. If logged in, the Login should disappear
- Create User. If user is logged in, create user option should not be displayed.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

See also the Demo Issue for more info. APIs include:

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by hkhual** [comment]
Created Handle 404s page in React Js from https://serverless-stack.com/chapters/handle-404s.html 
tutorial. 
Estimated Time: 7 Hours
Actual Time: TBD

**Comment by hkhual** [comment]
**The actokids signin page logic is working.** 
![actokids-home-signin](https://user-images.githubusercontent.com/24612635/54650621-aa900780-4a6c-11e9-8ef4-f7723992b0ab.JPG)

**Once the user logged in the navbar menu will changed into create event and sign up**
![dashboard-page](https://user-images.githubusercontent.com/24612635/54650666-d3b09800-4a6c-11e9-9628-ca47c68e3500.JPG)

**If the user click sign up, it will go back to sign in page.**

**Comment by hkhual** [comment]
Still need to figure out how to hide signout functions when the user logged in. The signup button still appear even the user is logged in. I will be looking at https://serverless-stack.com/chapters/add-the-session-to-the-state.html this tutorial

**Comment by hkhual** [comment]
**Time estimated:** 7 hours
**Time spent:** 12 hours
**Pull Request link:**
https://github.com/ActoKids/web-ui/pull/46 
https://github.com/ActoKids/web-ui/pull/53
https://github.com/ActoKids/web-ui/pull/61
**Wiki link:**
https://github.com/ActoKids/web-ui/wiki/User-logged-in-logic
**Deployed Code link:**
http://actokids-logged-logic.s3-website-us-east-1.amazonaws.com

**Who test this and what is the feedback?**
Erik and Yithong tested  User logged in logic page. Erik gave me feedback on an issue with Sign out because Sign out is not working property. After much research, I was able to find solutions to the problem.  


**What did you test and what is the feedback?**

I tested these pull requests 
https://github.com/ActoKids/web-ui/pull/44 Ran this PR and found no error. 
https://github.com/ActoKids/web-ui/pull/45 : moment.js library for date and time format
https://github.com/ActoKids/web-ui/pull/49 Tested Search Function 
https://github.com/ActoKids/web-ui/pull/50/  tested filter function in this PR. 


Bugs That I've worked on. 
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/120  @erikNeville
