### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by coultergeist** [ActoKids/AD440_W19_CloudPracticum#97]
For this final sprint, you must prepare error handling. After the demo, the API team will delete a function (work with API team to determine which function will be used). The UI team will then navigate to that page and the error message must display. See also the [Demo Issue](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/91) for more info.

Once assigned, annotate your estimated time. Then, keep regular updates on your issue. Comment your approach, tutorials, articles, updates, links, photos, etc. Comment often. When closing your issue include the following in your final comment.

Time estimated:
Time spent:
Pull Request link:
Wiki link:
Deployed Code link:
Testers:
What I tested:

**Comment by yahya09206** [comment]
Time estimated: 4
Time spent: 7
Pull Request link: https://github.com/ActoKids/web-ui/pull/51/commits/58dc918702ddd14963b45990c14b16dddc272049
Wiki link: https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/Error-Page
Deployed Code link: http://www-dev.2edusite.com/dashboard/me
Testers: hau tested that the error page was working on local machine
What I tested: I tested to see by going to a page that didn't exist then the error page would show up since I couldn't test it by turning of an api function.

<img width="877" alt="Screen Shot 2019-03-20 at 5 35 39 PM" src="https://user-images.githubusercontent.com/10914845/54727754-bc3de180-4b36-11e9-8c11-57c4918ade72.png">
