### ISSUE TITLE
1 bootstrap vulnerability found in yarn.lock

### ISSUE THREAD

**Issue by bmenaz** [ActoKids/AD440_W19_CloudPracticum#98]
1 bootstrap vulnerability found in yarn.lock
Details:
CVE-2019-8331
More information
moderate severity
Vulnerable versions: >= 4.0.0, < 4.3.1
Patched version: 4.3.1

In Bootstrap 4 before 4.3.1 and Bootstrap 3 before 3.4.1, XSS is possible in the tooltip or popover data-template attribute. For more information, see: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Solution:

Upgrade bootstrap to version 4.3.1 or later. For example:

bootstrap@^4.3.1:

version "4.3.1"

**Comment by hkhual** [comment]
As far as I am concerned, we do not use bootstrap in our code. We use NPM node package manager in our project. Our project does not need yarn.lock file because npm uses package-lock.json instead. when we run npx create-react-app React js automatically generated yarn.lock file. Since we don't use yarn.lock file, we can safely delete yarn.lock file.

**Comment by bmenaz** [comment]
Thanks on the response back. I will set the alert to “vulnerable code is not actually used” and dismiss the issue. I will leave the decision to delete the yarn file.
